### ISSUE TITLE
[Issue] keybind issue, may break gameplay

### ISSUE THREAD

**Issue by CoolLKKPS** [AndrewHack242/Ordered_Custom_Boombox#1]
@AndrewHack242 this mod [Hackattack242-ItemTertiaryUse_Conflict_Solver](https://thunderstore.io/c/lethal-company/p/Hackattack242/ItemTertiaryUse_Conflict_Solver/) u made are actually break something from `interact`, sometime i cannot pickup the Maneater (Maybe cause by this mod bc i don't have this issue previously)
i also did require some feature bc i want to change keybind, i use `E` to `**USE**` item: add custom keybinding support, remove [Hackattack242-ItemTertiaryUse_Conflict_Solver](https://thunderstore.io/c/lethal-company/p/Hackattack242/ItemTertiaryUse_Conflict_Solver/) dependency and add [InputUtils](https://thunderstore.io/c/lethal-company/p/Rune580/LethalCompany_InputUtils) as dependency

**Comment by CoolLKKPS** [comment]
oh and also conflict with `ButteryFixes`, cause u cannot use `Q` `E` keybinds on the boombox

**Comment by AndrewHack242** [comment]
@CoolLKKPS thanks for submitting the issue.

About the keybind thing, it should respond to your keybind changes in game, it overloads the vanilla game's function calls.

Also, the conflict solver should only trigger if your tertiary use and interact keys are the same button, otherwise the mod should do nothing.

If I could get the Thunderstore code for the modpack you are using, that would greatly help me debug all of this. Also, if you have specific steps to reproduce any of this, I would greatly appreciate that.

**Comment by CoolLKKPS** [comment]
first, i think u just need to install butteryfixes to reproduct issue, and sometime can break interact when u try to interact with the crying maneater
second, my modpack link: https://1drv.ms/f/c/c26722dc35962b5c/ElwrljXcImcggMKLCgAAAAABXdwXiAVT3j3zNnyNZw3uXg

**Comment by CoolLKKPS** [comment]
also, interact issue im pretty sure not only bc the custom keybind, i perfer bc butteryfixes think the item don't have secondary and tertiary item use, so that mod just block that, and if im right, u can easily reproduct that by simply install butteryfixes and this mod
same as interact with the maneater but a bit different, in that time when try to appease the crying maneater, the maneater somehow struggled down and then (might need) grabbed by the bug

**Comment by KeiFeeD** [comment]
When I take everything it doubles in inventory

**Comment by AndrewHack242** [comment]
I have confirmed that butteryfixes breaks the q/e interactions on the boombox, thanks for reporting this, I'll look into what I can do about it.

**Comment by AndrewHack242** [comment]
The modpack doesn't have this mod or Butteryfixes in it? It also doesn't have LethalLevelLoader despite having custom moons/interiors?

**Comment by AndrewHack242** [comment]
Also it appears that none of the actual mod files are there?

**Comment by AndrewHack242** [comment]
disregard, did not realize that you could import files into r2modman

**Comment by AndrewHack242** [comment]
@CoolLKKPS I can't seem to recreate the maneater issue, and I'm not sure how either of these mods would do that one.

**Comment by CoolLKKPS** [comment]
okay? i did a bit tired fixing my modpack so, if i have more evidence i will let u know!

**Comment by CoolLKKPS** [comment]
i think that fixed so, if i have issue i will re-poen this
