### ISSUE TITLE
Inventory issue

### ISSUE THREAD

**Issue by KeiFeeD** [AndrewHack242/Ordered_Custom_Boombox#2]
When I take item it doubles in inventory. And if I drop that item it's copy will be stay inventory, but item will not be in arms

**Comment by AndrewHack242** [comment]
Can you elaborate a bit? does this happen when picking up an item while holding the boombox? and how does this 'copy' work? does it go in a different slot than the 'real' one?

Does this happen any time you attempt to pick up an item?

**Comment by AndrewHack242** [comment]
And if you were using other mods, can you send me a modpack code or link?

**Comment by AndrewHack242** [comment]
Closing due to inability to reproduce
